export const POSTS = {
  INITIALISE: "INITIALISE_POSTS",
  CREATE_POST: "CREATE_POST",
};

export const USERS = {
  INITIALISE: "INITIALISE_USERS",
  USER_FOLLOW: "USER_FOLLOW",
};

export const AUTH = {
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  SET_BOOKMARKS: "SET_BOOKMARKS",
  USER_FOLLOW: "USER_FOLLOW",
};
